name: Publish Extension Pack

on:
  workflow_dispatch:
    inputs:
      pack:
        description: Extension Pack
        type: choice
        options:
          - authors
          - rpc
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22.x'

      - name: Install vsce
        run: npm install -g vsce

      - name: Package extension
        working-directory: extension-packs/draftforge-${{ inputs.pack }}
        run: vsce package

      - name: Publish to Visual Studio Marketplace
        working-directory: extension-packs/draftforge-${{ inputs.pack }}
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: vsce publish --pat $VSCE_PAT
